### ISSUE TITLE
signup and signin not working

### ISSUE THREAD

**Issue by Aadhi06** [mhutshow/DoctorAppointmentSystem#1]
Signup and signup shows authentication failed why is that

**Comment by mhutshow** [comment]
Cuz I have removed the googleservices.json file. Add your own firebase. It
will work.

**Comment by Aadhi06** [comment]
i have removed google services.json and add my one still not working

**Comment by Aadhi06** [comment]
its showing authentication failed signup and signin 
for google sign in nothing shows

**Comment by mhutshow** [comment]
may be u havnt set permission. check it properly. its working fine here.

**Comment by Aadhi06** [comment]
How to set permission which permission ur telling about?

**Comment by mhutshow** [comment]
I am talking about the Rules of Cloud Firestore.

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if
          request.time < timestamp.date(2025, 1, 5);
    }
  }
}

**Comment by Aadhi06** [comment]
http://i.prnt.sc/ENsGsAvETQ6WggF7qyfGtQ.png
this is the error

**Comment by Aadhi06** [comment]
![image](https://user-images.githubusercontent.com/64943047/127748141-f0750c45-63ba-4f23-9248-22080ad443bf.png)
